version: "3.8"
services:
  mongodb:
    image: mongo
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: admin
    # MONGO_INITDB_ROOT_PASSWORD: dbUserPassword
    volumes:
      - data:/data/db
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
